# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: helpingchatdb
  pool: 5
  username:
  password:
  template: template0
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: helpingchat_test
  pool: 5
  username: myapp
  password: password1