development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "0ea8d8885e5effb0b81691f43d31e33fa80bb1a10463ccfc514eb570cdfa264d"
  signature_expiration: 3600 # one hour
